export const SELECCIONAR_CLIENTE = "SELECCIONAR_CLIENTE";
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const CANTIDAD_PRDOUCTOS = "CANTIDAD_PRDOUCTOS";
export const ACTUALIZAR_TOTAL = "ACTUALIZAR_TOTAL";
